# Generated by cucumber-sinatra. (2013-11-13 20:53:50 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/myapp.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Scuplts

class ScupltsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ScupltsWorld.new
end
